import pg from "pg"
const { Pool } = pg
import { Kysely, PostgresDialect, Generated, ColumnType } from "kysely"
import {
  GetSecretValueCommand,
  SecretsManagerClient,
} from "@aws-sdk/client-secrets-manager"

const secretsManager = new SecretsManagerClient({
  region: process.env.AWS_REGION || "us-east-1",
})

const { SecretString: secret } = await secretsManager.send(
  new GetSecretValueCommand({
    SecretId: process.env.POSTGRES_SECRET_ARN,
  })
)
if (!secret) throw new Error("No secret found")

const credentials = JSON.parse(secret) as {
  username: string
  password: string
  engine: string
  host: string
  port: 5432
  dbname: string
  dbInstanceIdentifier: string
}

interface UserTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<string>

  email: string | null
  stripe_customer_id: string | null
  stripe_subscription_status: string | null

  // You can specify a different type for each operation (select, insert and
  // update) using the `ColumnType<SelectType, InsertType, UpdateType>`
  // wrapper. Here we define a column `modified_at` that is selected as
  // a `Date`, can optionally be provided as a `string` in inserts and
  // can never be updated:
  inserted_at: ColumnType<Date, string | undefined, string | undefined>
  updated_at: ColumnType<Date, string | undefined, string | undefined>
}

interface AskUserTable {
  id: Generated<string>

  ask_id: string
  user_id: string

  inserted_at: ColumnType<Date, string | undefined, string | undefined>
  updated_at: ColumnType<Date, string | undefined, string | undefined>
}

interface AskEventTable {
  id: Generated<string>

  user_id: string | null

  inserted_at: ColumnType<Date, string | undefined, string | undefined>
  updated_at: ColumnType<Date, string | undefined, string | undefined>
}

// Keys of this interface are table names.
interface Database {
  users: UserTable
  ask_events: AskEventTable
  asks_users: AskUserTable
}

// You'd create one of these when you start your app.
export const db = new Kysely<Database>({
  dialect: new PostgresDialect({
    pool: new Pool({
      host: process.env.POSTGRES_HOST,
      port: Number.parseInt(process.env.POSTGRES_PORT || "5432"),
      database: process.env.POSTGRES_DATABASE || credentials.dbname,
      user: process.env.POSTGRES_USER || credentials.username,
      password: process.env.POSTGRES_PASSWORD || credentials.password,
    }),
  }),
})
