const cspDirectives = [
  {
    directive: 'default-src',
    sources: ['*'],
  },
  {
    directive: 'script-src',
    sources: [
      "'self'",
      "'unsafe-eval'",
      "'unsafe-inline'",
      'https://*.statmuse.com',
      'https://cdn.statmuse.com',
      'https://api.statmuse.com',
      'https://*.33across.com',
      'https://*.adsafeprotected.com',
      'https://*.amazon-adsystem.com',
      'https://*.aniview.com',
      'https://*.casalemedia.com',
      'https://*.cloudflare.com',
      'https://*.doubleverify.com',
      'https://*.doubleclick.net',
      'https://encouragingthread.com',
      'https://*.encouragingthread.com',
      'https://*.extremereach.io',
      'https://*.fastclick.net',
      'https://*.indexww.com',
      'https://*.moatads.com',
      'https://*.ntv.io',
      'https://*.postrelease.com',
      'https://*.pub.network',
      'https://*.resonate.com',
      'https://*.sendtonews.com',
      'https://*.springserve.com',
      'https://*.yimg.com',
      'https://adservice.google.com',
      'https://apis.google.com',
      'app.sgwidget.com',
      'https://cdn.amplitude.com',
      'https://cdn.ampproject.org',
      'https://cdn.jsdelivr.net',
      'https://cdn.jwplayer.com',
      'https://cdn.segment.com',
      'https://cdn.syndication.twimg.com',
      'https://connect.facebook.net',
      'https://iframe.fresh8.co',
      'https://imasdk.googleapis.com',
      'https://pagead2.googlesyndication.com',
      'https://partner.googleadservices.com',
      'https://platform.twitter.com',
      'https://resources.usersnap.com',
      'https://s.tradingview.com',
      'https://s0.2mdn.net',
      'https://s3.tradingview.com',
      'https://securepubads.g.doubleclick.net',
      'https://ssl.p.jwpcdn.com',
      'https://tpc.googlesyndication.com',
      'https://widget.usersnap.com',
      'https://www.google-analytics.com',
      'https://www.googletagmanager.com',
      'https://www.googletagservices.com',
      'https://www.gstatic.com',
      'https://r.wdfl.co',
    ],
  },
  {
    directive: 'style-src',
    sources: [
      "'self'",
      "'unsafe-inline'",
      'https://*.pub.network',
      'https://*.cloudflare.com',
      'https://cdn.statmuse.com',
      'https://cdn.jsdelivr.net',
      'https://fonts.googleapis.com',
      'https://maxcdn.bootstrapcdn.com',
      'https://p.typekit.net',
      'https://platform.twitter.com',
      'https://themes.googleusercontent.com',
      'https://ton.twimg.com',
      'https://use.typekit.net',
    ],
  },
  {
    directive: 'connect-src',
    sources: [
      "'self'",
      'https://*.statmuse.com',
      'https://*.3lift.com',
      'https://*.33across.com',
      'https://*.adnxs.com',
      'https://*.adsafeprotected.com',
      'https://*.adsrvr.org',
      'https://*.amazon-adsystem.com',
      'https://*.bidswitch.net',
      'https://*.casalemedia.com',
      'https://*.cloudfront.net',
      'https://*.doubleclick.net',
      'https://*.doubleverify.com',
      'https://*.flashtalking.com',
      'https://*.fwmrm.net',
      'https://*.googlesyndication.com',
      'https://*.innovid.com',
      'https://*.jwplayer.com',
      'https://*.jwpsrv.com',
      'https://*.kargo.com',
      'https://*.media.net',
      'https://*.pub.network',
      'https://*.pubmatic.com',
      'https://*.reson8.com',
      'https://*.rkdms.com',
      'https://*.rlcdn.com',
      'https://*.rubiconproject.com',
      'https://*.sendtonews.com',
      'https://*.springserve.com',
      'https://*.stnvideo.com',
      'https://*.technoratimedia.com',
      'https://*.undertone.com',
      'https://*.unrulymedia.com',
      'https://*.yahoo.com',
      'https://api.statmuse.com',
      'api.amplitude.com',
      'https://api.getrewardful.com',
      'https://api.honeybadger.io',
      'https://api.segment.io',
      'https://app.sgwidget.com',
      'https://cdn.segment.com',
      'https://csi.gstatic.com',
      'https://entitlements.jwplayer.com',
      'https://pagead2.googlesyndication.com',
      'https://secure.gravatar.com',
      'https://securepubads.g.doubleclick.net',
      'https://stats.g.doubleclick.net',
      'https://videos-fms.jwpsrv.com',
      'https://widget.usersnap.com',
      'https://www.facebook.com',
      'https://www.google-analytics.com',
      'wss://www.statmuse.com',
    ],
  },
  {
    directive: 'font-src',
    sources: [
      "'self'",
      'chrome-extension:',
      'data:',
      'https://cdn.statmuse.com',
      'https://fonts.gstatic.com',
      'https://maxcdn.bootstrapcdn.com',
      'https://use.typekit.net',
      'https://*.cloudflare.com',
    ],
  },
  {
    directive: 'img-src',
    sources: ['*', 'data:'],
  },
  {
    directive: 'media-src',
    sources: ['*', 'blob:'],
  },
  {
    directive: 'worker-src',
    sources: ['blob:'],
  },
]

export const contentSecurityPolicy = cspDirectives
  .map(({ directive, sources }) => `${directive} ${sources.join(' ')};`)
  .join(' ')
